# Организация программ и методы строк
print('Практическая работа по уроку "Организация программ и методы строк"')
my_string=input('Введите строку предложение": ')
print(len(my_string))
print(my_string.upper())
print(my_string.lower())
my_string=my_string.replace(' ','')
print(my_string)
print(my_string[0])
print(my_string[-1])